# This is a basic workflow to help you get started with Actions

name: Build PL\Java 1.5.x on Java 8 for Postgres 14.

on:
  push:
    branches: [ "main" ]
  workflow_dispatch

env:
  JAR_DIR: pljava/pljava-packaging/target
  JAR_FILE: pljava-pg14.*-amd64-Linux-gpp.jar

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check out PL/Java
      uses: actions/checkout@v3
      with:
        repository: tada/pljava
        path: pljava
        ref: V1_5_8

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'

    - name: Report Java, Maven, and PostgreSQL versions (Linux, macOS)
      run: |
        java -version
        mvn --version
        pg_config

    - name: Install PG dev files (Ubuntu, PGDG)
      run: |
        echo deb http://apt.postgresql.org/pub/repos/apt \
          "$(lsb_release -cs)-pgdg" main |
        sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        sudo apt-get install postgresql-server-dev-14 libkrb5-dev

    - name: Build PL\Java
      working-directory: pljava
      run: |
        mvn clean install

    - name: Upload compiled files
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ${{ github.workspace }}/${{ env.JAR_DIR }}/
        retention-days: 1

    - name: Install JAR
      run: JAR=$(ls $GITHUB_WORKSPACE/$JAR_DIR/$JAR_FILE) && sudo java -jar $JAR
